HHVM_EXTENSION(h3 ext_h3.cpp)
HHVM_SYSTEMLIB(h3 ext_h3.php)

find_path(BZIP_INCLUDE_PATH NAMES bzlib.h)
find_library(BZIP_LIBRARY NAMES bz2)
if (NOT BZIP_INCLUDE_PATH OR NOT BZIP_LIBRARY)
  message(FATAL_ERROR "Unable to find libbz2")
endif()
include_directories(${BZIP_INCLUDE_PATH})
target_link_libraries(h3 ${BZIP_LIBRARY})

include(CheckSymbolExists)
set(CMAKE_REQUIRED_LIBRARIES ${BZIP_LIBRARY})
Check_Symbol_Exists(BZ2_bzlibVersion "bzlib.h" BZIP_VERSION_CALL)
if (BZIP_VERSION_CALL)
  add_definitions("-DHAVE_BZ2_VERSION")
endif()
